/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica4;
import java.awt.event.ItemEvent;
/**
 *
 * @author juanjo
 */
public class Internacionalizacion extends javax.swing.JFrame {

    /**
     * Creates new form Internacionalizacion
     */
    
    public Internacionalizacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        spanishButton = new javax.swing.JToggleButton();
        englishButton = new javax.swing.JToggleButton();
        americanButton = new javax.swing.JToggleButton();
        originLabel = new javax.swing.JLabel();
        originTextField = new javax.swing.JTextField();
        destinationLabel = new javax.swing.JLabel();
        destinationTextField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        kmLabel = new javax.swing.JLabel();
        kmTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(4, 232, 254));

        jPanel1.setBackground(new java.awt.Color(4, 232, 254));

        Title.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Agenda de Viajes");

        spanishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spanish-flag.png"))); // NOI18N
        spanishButton.setToolTipText("Cambiar a español");
        spanishButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                spanishButtonItemStateChanged(evt);
            }
        });

        englishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/english-flag.png"))); // NOI18N
        englishButton.setToolTipText("Cambiar a inglés británico");
        englishButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                englishButtonStateChanged(evt);
            }
        });

        americanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/american-flag.png"))); // NOI18N
        americanButton.setToolTipText("Cambiar a inglés americano");
        americanButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                americanButtonStateChanged(evt);
            }
        });

        originLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        originLabel.setForeground(new java.awt.Color(255, 255, 255));
        originLabel.setText("Origen");

        originTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        originTextField.setToolTipText("Introduce el origen");

        destinationLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        destinationLabel.setForeground(new java.awt.Color(255, 255, 255));
        destinationLabel.setText("Destino");

        destinationTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        destinationTextField.setToolTipText("Introduce el destino");

        dateLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Fecha");

        dateTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateTextField.setToolTipText("Introduce la fecha");

        kmLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        kmLabel.setForeground(new java.awt.Color(255, 255, 255));
        kmLabel.setText("Kilómetros");

        kmTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kmTextField.setToolTipText("Introduce los kilómetros");

        priceLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("Precio");

        priceTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priceTextField.setToolTipText("Introduce el precio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(spanishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(englishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(originLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kmLabel)
                            .addComponent(priceLabel)
                            .addComponent(destinationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(originTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(americanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(americanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(englishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(spanishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(originTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setLanguage(int opt){
        switch(opt) {
            case 0:
              // Spanish
                Title.setText("Agenda de Viajes");
                originLabel.setText("Origen");
                destinationLabel.setText("Destino");
                dateLabel.setText("Fecha");
                kmLabel.setText("Kilómetros");
                priceLabel.setText("Precio");
                
                originTextField.setText("Italia");
                destinationTextField.setText("España");
                dateTextField.setText("19/02/2019");
                kmTextField.setText("305 km");
                priceTextField.setText("503 €");
                
                originLabel.setToolTipText("Introduce el origen");
                destinationLabel.setToolTipText("Introduce el destino");
                dateLabel.setToolTipText("Introduce la fecha");
                kmLabel.setToolTipText("Introduce la distancia");
                priceLabel.setToolTipText("Introduce el precio");
                
                spanishButton.setToolTipText("Cambiar a español");
                englishButton.setToolTipText("Change to british english");
                americanButton.setToolTipText("Change to american english");
              break;
            case 1:
              // Englis
                Title.setText("Trips Agenda");
                
                originLabel.setText("Origin");
                destinationLabel.setText("Destination");
                dateLabel.setText("Date");
                kmLabel.setText("Kilometers");
                priceLabel.setText("Price");
                
                originTextField.setText("Italy");
                destinationTextField.setText("Spain");
                dateTextField.setText("19/02/2019");
                kmTextField.setText("305 km");
                priceTextField.setText("503 £");
                
                originLabel.setToolTipText("Enter the origin");
                destinationLabel.setToolTipText("Enter the destination");
                dateLabel.setToolTipText("Enter the date");
                kmLabel.setToolTipText("Enter the distance");
                priceLabel.setToolTipText("Enter the price");
                
                spanishButton.setToolTipText("Cambiar a español");
                englishButton.setToolTipText("Change to british english");
                americanButton.setToolTipText("Change to american english");
              break;
            case 2:
                // American
                Title.setText("Trips Agenda");
                
                originLabel.setText("Origin");
                destinationLabel.setText("Destination");
                dateLabel.setText("Date");
                kmLabel.setText("Miles");
                priceLabel.setText("Price");
                
                originTextField.setText("Italy");
                destinationTextField.setText("Spain");
                dateTextField.setText("02/19/2019");
                kmTextField.setText("305 miles");
                priceTextField.setText("503 $");
                
                originLabel.setToolTipText("Enter the origin");
                destinationLabel.setToolTipText("Enter the destination");
                dateLabel.setToolTipText("Enter the date");
                kmLabel.setToolTipText("Enter the distance");
                priceLabel.setToolTipText("Enter the price");
                
                spanishButton.setToolTipText("Cambiar a español");
                englishButton.setToolTipText("Change to british english");
                americanButton.setToolTipText("Change to american english");
                break;
            default:
              // code block
        }
    }
    
    
    private void spanishButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_spanishButtonItemStateChanged
        // TODO add your handling code here:
        if(spanishButton.getModel().isSelected() == true){
            spanishButton.setSelected(true);
            englishButton.setSelected(false);
            americanButton.setSelected(false);
            this.setLanguage(0);
        }
    }//GEN-LAST:event_spanishButtonItemStateChanged

    private void englishButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_englishButtonStateChanged
        // TODO add your handling code here:
        if(englishButton.getModel().isSelected() == true){
            spanishButton.setSelected(false);
            englishButton.setSelected(true);
            americanButton.setSelected(false);
            this.setLanguage(1);
        }
    }//GEN-LAST:event_englishButtonStateChanged

    private void americanButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_americanButtonStateChanged
        // TODO add your handling code here:
        if(americanButton.getModel().isSelected() == true){
            spanishButton.setSelected(false);
            englishButton.setSelected(false);
            americanButton.setSelected(true);
            this.setLanguage(2);
        }
    }//GEN-LAST:event_americanButtonStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Internacionalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Internacionalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Internacionalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Internacionalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Internacionalizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JToggleButton americanButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JToggleButton englishButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kmLabel;
    private javax.swing.JTextField kmTextField;
    private javax.swing.JLabel originLabel;
    private javax.swing.JTextField originTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    public javax.swing.JToggleButton spanishButton;
    // End of variables declaration//GEN-END:variables
}
