/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componente;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.ArrayList;


/**
 *
 * @author juanjo
 */
public class component extends javax.swing.JPanel {
    private String text_;
    private ArrayList<String> images_;
    private int num_images_ = 9;
    private int actual_position_ = -1;
    private int new_num_images = 8;
    private boolean first = true;
    
    /**
     * Creates new form component
     */
    public component() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 248, 202));

        jLabel2.setBackground(new java.awt.Color(235, 244, 121));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean showImage(int pos){
        boolean image_read = false;
        if(getClass().getResource((this.images_.get(pos))) != null && jLabel2.getIcon() == null){
            ImageIcon ii = new ImageIcon(getClass().getResource((this.images_.get(pos))));
            Image image = ii.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
            ii = new ImageIcon(image);
            jLabel2.setIcon(ii);
            image_read = true;
        }else if(jLabel2.getIcon() != null){
            jLabel2.setIcon(null);
            ImageIcon ii = new ImageIcon(getClass().getResource((this.images_.get(pos))));
            Image image = ii.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
            ii = new ImageIcon(image);
            jLabel2.setIcon(ii);
            image_read = true;
        }else{
            image_read = false;
        }
        return image_read;
    }
    
    public void setText(String text){
        this.text_ = text;
        //jTextField1.setText(this.text_);
    }
    public String getText(){
        //return jTextField1.getText();
        return "";
    }
    
    
    public void renderImages(){
        this.images_ = new ArrayList<String>();
        if(this.first == false){
            for(int i=0; i<=this.new_num_images; i++){
                String image = "/images/image-" + i + ".png";
                this.images_.add(image);
            }
        }else{
            for(int i=0; i<=this.num_images_; i++){
                String image = "/images/image-" + i + ".png";
                this.images_.add(image);
            }
        }
        this.actual_position_ = 0;
    }
    
    public void clearImages(){
        this.images_.clear();
        this.actual_position_ = 0;
        jLabel2.setIcon(null);
    }
    
    public void setFirstFalse(){
        this.first = false;
    }
    
    public boolean setNumImages(int images){
        images = images - 1;
        if(images < this.num_images_ && images >= 0){
            this.new_num_images = images;
            return true;
        }else{
            return false;
        }
    }
    public int getNumImages(){
        return this.new_num_images;
    }
  
    public int getPosition(){
        return this.actual_position_;
    }
    public boolean incrementPos(){
        boolean ismore = true;
        if(this.actual_position_ < this.num_images_){
            this.actual_position_++;
        }else{
            ismore = false;
        }
        return ismore;
    }
    public boolean decrementPos(){
        boolean ismore = true;
        if(this.actual_position_ > 0){
            this.actual_position_--;
        }else{
            ismore = false;
        }
        return ismore;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
